trigger ContactTrigger on Contact (before insert, after insert) {

    //Criar registro de conta sempre que um novo contato for criado sem uma conta.
    list<account> acclist = new list<account>();
    list<contact> cttlist = new list<contact>();
    
    for(Contact c: trigger.new){
        if(c.AccountId == null){
            Account a = new Account(Name = 'autoGenerated account');
            //c.AccountId = a.Id;
            acclist.add(a);
        }
    }
    system.debug('contasd ' + acclist);
    if(acclist.size() > 0){
        insert acclist; 
    }
}